version: '3.1'

services:

  postgres:
    image: postgres
    #volumes:
    #  - ./01-script-init.sql:/docker-entrypoint-initdb.d/01-script-init.sql
    environment:
      POSTGRES_PASSWORD: "siscacspass"
    ports:
      - "5432:5432"
    restart: unless-stopped
